### ISSUE TITLE
Exception raised: Num lines returned 49 != 180 Num lines input

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#150]
An exception was encountered in [this session](https://transfer.sh/qaj3q/session.smh) using version 1341089\* on Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)]:

``` python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP/SMH/smhr/smh/gui/chemical_abundances.py", line 737, in measure_all
    self.parent.session.measure_abundances()

  File "/Users/maudegull/Desktop/UROP/SMH/smhr/smh/session.py", line 889, in measure_abundances
    self.stellar_photosphere, transitions[finite])

  File "/Users/maudegull/Desktop/UROP/SMH/smhr/smh/radiative_transfer/moog/cog.py", line 121, in abundance_cog
    raise RTError("Num lines returned {} != {} Num lines input".format(len(transitions_array),len(transitions)))

RTError: Num lines returned 49 != 180 Num lines input
```

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/14di8I/screenshot.png)

**Additional details on how this exception occurred**:

When pressing measure all acceptable

**Comment by alexji** [comment]
I've found this pretty much always happens because of a problem in the line list or equivalent widths (e.g. REW = -10 or something like that). I'm just going to close it because it is technically being handled in the terminal, and a new issue can be made if this is really a problem.
