### ISSUE TITLE
Exception raised: list index out of range

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#189]
An exception was encountered in [this session](https://transfer.sh/JIJfZ/session.smh) using version 2b5e232\* on Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)]:

``` python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP/SMH/smhr/smh/gui/stellar_parameters.py", line 1854, in data
    spectral_model = self.spectral_models[index.row()]

IndexError: list index out of range
```

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/ZNDdL/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
This is fixed in v0.2 (I think)
