### ISSUE TITLE
Convert from old session files

### ISSUE THREAD

**Issue by andycasey** [andycasey/smhr#20]
- [ ] Detect old session format (trivial, because filename extensions within the .smh tarball)
- [ ] A converter function that is separate from the GUI _and_ model which converts old SMH session formats into new SMH sessions
- [ ] In the model (terminal), log a warning that the session has been converted to the new format upon loading
- [ ] In the GUI, show a warning the first time a session is to be converted over. But, don't allow "save" to simply write over the old SMH file -- the first save should behave like a "save as" in the standard GUI and force the user to explicitly specify that they want to overwrite the old session file.

**Comment by alexji** [comment]
A basic version of this has been done in `legacy.py`, I don't anticipate more being needed.
