### ISSUE TITLE
Strange spectrum stitching dispersion

### ISSUE THREAD

**Issue by alexji** [andycasey/smhr#219]
Our default spectrum stitching creates nonlinear dispersion in a weird way. Here's a typical MIKE stitched spectrum. It especially has trouble in the overlap region between red and blue. 

<img width="592" alt="screen shot 2017-01-10 at 9 11 34 pm" src="https://cloud.githubusercontent.com/assets/3082382/21836346/6ddfd4f4-d779-11e6-986d-74f6aaa3fc53.png">

@andycasey does this make sense to you based on your stitching algorithm? Is there a simple fix we can make to improve it?

**Comment by alexji** [comment]
I have found that the overlap region is very messed up and doesn't work well with the current stitching algorithm. Essentially, you don't get to bin the results so everything is very noisy. This matters when you really do need to add the S/N from lots of different pieces that are offset. It is also scientifically relevant e.g. because the 5018 Fe II line is there, and is often one of the few Fe II lines available in low S/N metal-poor stars (where even a bad measurement with large error is better than no measurement).

I have made a "better" algorithm in d8bfed2e0240866de4299c6f04f256ecca97e761 that just creates many small patches of linear dispersion. It then has to interpolate the ivar to the new dispersion, and this is not conserved. Some quick tests show this does well a lot of the time (since the interpolation tends to be in low-ivar regions), but bad in some cases (including parts of the overlap region). However I think the right thing to do is to do flux-conserving interpolation on the ivar with this new dispersion map.

@andycasey what do you think?

Old stitching:
![image](https://user-images.githubusercontent.com/3082382/29102997-e56e9792-7c71-11e7-8ce1-9f809e6a6ff7.png)

New stitching:
![image](https://user-images.githubusercontent.com/3082382/29103004-ebfe4e04-7c71-11e7-84c3-31bc8778b148.png)

**Comment by andycasey** [comment]
Looks good to me. 

The only thing I would change -- from an algorithmic point of view -- is to put the default interpolation values for flux as 1 (or better yet, nan), and 0 for ivar (which is interpreted as zero information). Then when summing, those will have zero weight already. 

Merge when you are happy (if it's not in master already)

**Comment by alexji** [comment]
Merged into remove-global-linelist (my current working branch with the GUI upgrades).

0*np.nan = np.nan unfortunately, so I don't think we can do that. Setting the flux default = 1 doesn't always work, e.g. you could very reasonably use this same algorithm to stitch unnormalized spectra. So  think it's better to keep as is.

Closing issue, although we should remain aware that ivar is not currently conserved.
