### ISSUE TITLE
Exception raised: 'W'

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#226]
An exception was encountered using version 64028fc on Python 2.7.6 | 32-bit | (default, Sep 15 2014, 17:36:57) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr/smh/gui/chemical_abundances.py", line 1778, in clicked_btn_update_abund_table
    abund = summary_dict[elem][1]

KeyError: 'W'
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/10CWXY/screenshot.png)

**Additional details on how this exception occurred**:
Happens when I try to measure tungsten on one of my stars, but doesn't happen with the rest of my stars

**Comment by alexji** [comment]
Closing because we don't measure W
