### ISSUE TITLE
Exception raised: invalid fmt: u'%.4e'

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#248]
An exception was encountered using version 6e9f017 on Python 2.7.6 | 32-bit | (default, Sep 15 2014, 17:36:57) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr/smh/gui/ui_mainwindow.py", line 424, in save_session
    self.session.save(self.session_path, overwrite=True)

  File "/Users/madelyncain/smhr/smh/session.py", line 237, in save
    self.normalized_spectrum.write(twd_path)

  File "/Users/madelyncain/smhr/smh/specutils/spectrum.py", line 388, in write
    np.savetxt(filename, a, fmt="%.4e")

  File "/Users/madelyncain/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1200, in savetxt
    raise ValueError('invalid fmt: %r' % (fmt,))

ValueError: invalid fmt: u'%.4e'
````

**Additional details on how this exception occurred**:

**Comment by maddiecain** [comment]
Hey alex, can you tell me how to get rid of this error? I pulled the most recent version and it's preventing me from saving

**Comment by maddiecain** [comment]
Trying to pull this fix - is getting this message a problem? 
Your configuration specifies to merge with the ref 'refs/heads/alex-mods'
from the remote, but no such ref was fetched.
I've been looking on how to solve it in stack exchange but i'm afraid I'll mess things up  if i start trying things

**Comment by alexji** [comment]
Sorry I deleted the alex-mods branch after I merged it into the master
branch. You can use that instead! Checkout master and pull.

**Comment by maddiecain** [comment]
thank you!

**Comment by maddiecain** [comment]
To get moog with mac if i already have gfortran, can i just run make -f Makefile.maclapsilent?

**Comment by alexji** [comment]
The installation instructions are at the bottom of the repo: https://github.com/alexji/moog17scat

**Comment by maddiecain** [comment]
I know i was just a bit confused

**Comment by alexji** [comment]
Ahh okay sorry I was confused; yes that should be the right thing to do.

**Comment by maddiecain** [comment]
Thanks that worked!
