### ISSUE TITLE
Fit disappears once you press "fit model" on synthesis

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#249]
<img width="1198" alt="screen shot 2017-08-04 at 10 37 21 pm" src="https://user-images.githubusercontent.com/13720061/28997478-95174b58-79ca-11e7-9279-592a56a89d40.png">

**Comment by alexji** [comment]
Oh dear I have done something really bad. I did not give enough significant figures for the spectrum dispersion, so a lot of points have been fixed to their nearest 0.1A. That is probably why the spectrum has looked funny too.

I will push a fix shortly.

**Comment by alexji** [comment]
OK I'm really sorry about this, but I tried to reduce the file size of the spectrum. I messed up and did it in scientific notation, which didn't give enough significant figures in the wavelength (only to 0.1A). So when you load a file, it will lose that resolution. This is why the plotting messed up for almost everything.

After you pull the bugfix, you can get back the correct normalized spectrum by going to the Normalize tab and re-normalizing. This will create a new normalized spectrum. Then after you save, there now should be enough significant figures saved for this to work.

**Comment by maddiecain** [comment]
Gotcha. I have files from before then with all the lines measured, so it shouldn't be an issue (i think). I was a bit concerned about why the spectrum looked so weird haha
