### ISSUE TITLE
Exception raised: Num lines returned 211 != 307 Num lines input

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#250]
An exception was encountered using version c9b3180 on Python 2.7.6 | 32-bit | (default, Sep 15 2014, 17:36:57) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr/smh/gui/stellar_parameters.py", line 1121, in measure_abundances
    filtering=filtering)

  File "/Users/madelyncain/smhr/smh/session.py", line 884, in stellar_parameter_state
    self.stellar_photosphere, transitions[finite], twd=self.twd)

  File "/Users/madelyncain/smhr/smh/radiative_transfer/moog/cog.py", line 121, in abundance_cog
    raise RTError("Num lines returned {} != {} Num lines input".format(len(transitions_array),len(transitions)))

RTError: Num lines returned 211 != 307 Num lines input
````

**Additional details on how this exception occurred**:

**Comment by maddiecain** [comment]
Happens when you press "measure abundances " on stellar parameters or chemical abundances tab

**Comment by alexji** [comment]
Can you send me the session where this happened?

**Comment by alexji** [comment]
There appears to be a problem with MOOG (it is giving insane abundances for many lines) that I will look into.

**Comment by maddiecain** [comment]
I'll email it yeah

**Comment by alexji** [comment]
OK this is a problem with MOOG not SMHR so closing the issue. I had messed something up and it should be fixed on that other repo shortly.
