### ISSUE TITLE
Exception raised: 'Pd'

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#253]
An exception was encountered using version 81b17fd on Python 2.7.6 | 32-bit | (default, Sep 15 2014, 17:36:57) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr/smh/gui/chemical_abundances.py", line 1914, in clicked_btn_update_abund_table
    abund = summary_dict[elem][1]

KeyError: 'Pd'
````

**Additional details on how this exception occurred**:
Happens with Lu and a few other elements that aren't usually measured

**Comment by alexji** [comment]
I pushed something that should fix this, but I didn't test to see if it would work or if it would cause problems downstream. I don't think either of those will be a problem though.

Just wanted to check: in these cases, is the synthesis just for a single element (e.g. Pd or Lu) or are you trying to fit multiple elements at once?

**Comment by maddiecain** [comment]
synthesis of a single element, sometimes if i go to another line and come back the issue is fixed (it was in this case). so its not a really important bug
