### ISSUE TITLE
Exception raised: u'synthesized_dispersion'

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#259]
An exception was encountered in [this session](https://transfer.sh/XrwTj/session.smh) using version f7611a6 on Python 2.7.12 |Anaconda 2.4.1 (x86_64)| (default, Jul  2 2016, 17:43:17) [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP/SMH_NEW/smhr/smh/gui/chemical_abundances.py", line 1947, in clicked_export_synthesis
    spectral_model.export_fit(synth_path, data_path, param_path)

  File "/Users/maudegull/Desktop/UROP/SMH_NEW/smhr/smh/spectral_models/synthesis.py", line 454, in export_fit
    disp = self.metadata["synthesized_dispersion"]

KeyError: u'synthesized_dispersion'
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/rUaWy/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by mgull19** [comment]
when trying to export
also this happend to the synthesis
![bildschirmfoto 2017-08-31 um 15 58 38](https://user-images.githubusercontent.com/19806342/29942880-5b5399ee-8e65-11e7-84ec-b94ea03ab5c7.png)

**Comment by alexji** [comment]
Can you push "synthesize" and then try again?

**Comment by mgull19** [comment]
nothing changes still looks like this

**Comment by alexji** [comment]
That may be, but I think the exporting should work correctly after you
press synthesize

**Comment by alexji** [comment]
It seems like the exporting worked so closing the issue. This entire branch is just a hack for @mgull19 to get something done now, someday I will go through and figure out a better solution.
