### ISSUE TITLE
Matplotlib version 2.0 incompatible

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#264]
An exception was encountered in [this session](https://transfer.sh/UXfaU/session.smh) using version 88cde87* on Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/iCloud Drive (Archiv)/Desktop/UROP_FREBEL/smhr/smh/gui/stellar_parameters.py", line 691, in measure_abundances
    self.update_scatter_plots()

  File "/Users/maudegull/iCloud Drive (Archiv)/Desktop/UROP_FREBEL/smhr/smh/gui/stellar_parameters.py", line 549, in update_scatter_plots
    _, (ex_yerr_top, ex_yerr_bot), (ybars, ) = ex_container

ValueError: need more than 0 values to unpack
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/vddte/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
This session works just fine on my computer, and so it's likely a problem with the matplotlib version. 

I have:
```
In [1]: import matplotlib
In [2]: matplotlib.__version__
Out[2]: '1.5.1'
```

Can you check to see what version you have?

**Comment by mgull19** [comment]
In [1]: import matplotlib

In [2]: matplotlib.__version__
Out[2]: '2.0.0'

In [3]:

**Comment by alexji** [comment]
Ok thanks. We should fix the code so this is compatible with version 2.0
but in the meantime you can downgrade to v1.5 and it should work.

Leaving issue open to look at v2.0.

**Comment by alexji** [comment]
See #306; work in progress

**Comment by alexji** [comment]
Closing issue since PR is made
