### ISSUE TITLE
Measurements won't update when unchecking a line

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#266]
Happens with both synthesis and EW, when i uncheck a line the measurements on the top panel won't update

**Comment by alexji** [comment]
Which tab?

**Comment by maddiecain** [comment]
Line Measurements

**Comment by alexji** [comment]
OK, and is this the top spectrum plot or the little summary line? I think I
have forgotten to link the summary line to check/uncheck. For now I think
you can refresh it by changing elements then changing back...or refreshing
the table.
