### ISSUE TITLE
Review tab has a big issue

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#267]
When I select points on the review tab, a lot of the ones that show up aren't selected, and many of the selected points do show up. I attached an example image.

<img width="1280" alt="screen shot 2017-09-26 at 3 24 24 am" src="https://user-images.githubusercontent.com/13720061/30847632-392a53bc-a26a-11e7-8983-d798472d8b93.png">

**Comment by alexji** [comment]
Yes, I have to do a code upgrade to show unacceptable points as different
symbols, but in the meantime you can hide them by hiding the "unacceptable"
points.

**Comment by maddiecain** [comment]
Gotcha. Some of the acceptable points don't show up as well, though

**Comment by alexji** [comment]
Do they appear if you refresh the table? There's some state problems I
haven't totally figured out, so I added the refresh button for this purpose.

**Comment by alexji** [comment]
Are the points still missing if you push refresh? I won't be able to fix the problem fully for a while but it should still function.

**Comment by alexji** [comment]
(Closing since this is not something I can resolve for a while and doesn't impact functionality)
