### ISSUE TITLE
Make window come to front once finished fitting

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#269]
This is more of a suggestion, but some of the synthesis fits take a really long time. It would be nice for the SMH window to come to the front of the screen when it's done fitting so if I go to another tab while I'm waiting I"ll be notified when it finishes

**Comment by alexji** [comment]
After the most recent pull, if in your `.smh_session.defaults` you put
```
bring_to_top_after_fit: 1
```

It should now do this.
