### ISSUE TITLE
Exception raised: u'plot_x'

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#274]
An exception was encountered using version ce1a9b2 on Python 2.7.6 | 32-bit | (default, Sep 15 2014, 17:36:57) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr/smh/gui/chemical_abundances.py", line 1402, in clicked_export_synthesis
    spectral_model.export_fit(synth_path, data_path, param_path)

  File "/Users/madelyncain/smhr/smh/spectral_models/synthesis.py", line 509, in export_fit
    synth_spec = Spectrum1D(meta["plot_x"], meta["plot_y"], ivar)

KeyError: u'plot_x'
````

**Additional details on how this exception occurred**:

**Comment by maddiecain** [comment]
Happens when I try and export a synthesis line measurements

**Comment by alexji** [comment]
This usually means you haven't run a synthesis on this measurement since
updating to the newest version of SMHR

**Comment by maddiecain** [comment]
that's probably it, thanks!
