### ISSUE TITLE
Modified default behavior for negative flux values in spectrum

### ISSUE THREAD

**Issue by alexji** [andycasey/smhr#279]
This is an issue just for discussion purposes.

When reading spectra from files, SMHR currently makes all negative values into nan.
For spectra with low S/N, or previously-normalized spectra (e.g. dividing out flats), this removes a lot of pixels that have information but possible bad reductions.

Instead, I have changed this so that it just turns the ivar into a small number but keeps the flux value.
(It is not in v0.2 or on master yet, only in this commit: 1251394f5b19a72640fc4944f233e64aef5464d3.)

@andycasey what do you think?

**Comment by andycasey** [comment]
Seems reasonable to me.
