### ISSUE TITLE
Show file path somewhere

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#280]
This isn't an issue, but I think it would be nice to show the file path/name somewhere in the window, so you can tell what file you have open

**Comment by alexji** [comment]
This is a good idea, I'll implement it soon. Is a reasonable solution that
the title bar should have the name of the .smh file?

**Comment by maddiecain** [comment]
Yes, that would be good, but I also think having the path somewhere (maybe bottom left) would be nice because a lot of programs require the path as input and if you have a bunch of files for the same star, it can get confusing

**Comment by alexji** [comment]
I can make it so that the path goes in the summary comment box by default
when you create a new file, would that work? I don’t know how to put
something in the bottom left and am worried about overcrowding the UI

**Comment by maddiecain** [comment]
Yeah that would be great!

**Comment by alexji** [comment]
OK now when loading, it will either display the "OBJECT" in the original FITS header in the title bar, or the name of the SMHR file if that doesn't exist.

When making a new file, it adds the spectrum files in the notes.
