### ISSUE TITLE
Exception raised: Old spectral model format! (v<0.2)(hashes instead of linelist) Cannot load

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#284]
An exception was encountered using version 99a8ff1 on Python 2.7.14 |Anaconda custom (x86_64)| (default, Mar 12 2018, 07:39:26) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/iCloud Drive (Archiv)/Desktop/UROP_FREBEL/smhr/smh/gui/ui_mainwindow.py", line 402, in open_session
    self.session = smh.Session.load(path)

  File "/Users/maudegull/iCloud Drive (Archiv)/Desktop/UROP_FREBEL/smhr/smh/session.py", line 438, in load
    reconstructed_spectral_models = session.reconstruct_spectral_models(spectral_model_states)

  File "/Users/maudegull/iCloud Drive (Archiv)/Desktop/UROP_FREBEL/smhr/smh/session.py", line 344, in reconstruct_spectral_models
    raise IOError("Old spectral model format! (v<0.2)"

IOError: Old spectral model format! (v<0.2)(hashes instead of linelist) Cannot load
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/B8IVn/screenshot.png)

**Additional details on how this exception occurred**:

When trying to open SMH file after git pull

**Comment by alexji** [comment]
Can you send me the file you tried to open? It looks like it’s an old file
that hasn’t been converted to v0.2

**Comment by alexji** [comment]
Confirmed this is an old session (created in v0.1).

You can use scripts/convert_v01_to_v02.py to convert this into the correct format.
