### ISSUE TITLE
Exception raised: 'NoneType' object has no attribute 'row'

### ISSUE THREAD

**Issue by HonggeunKim** [andycasey/smhr#285]
An exception was encountered in [this session](https://transfer.sh/XwGO7/session.smh) using version None on Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  7 2017, 17:05:42) [GCC 7.2.0]:

````python
Traceback (most recent call last):

  File "/home/honggeun/smhr-0.2/smh/gui/base.py", line 965, in contextMenuEvent
    self.menu_finished()

  File "/home/honggeun/smhr-0.2/smh/gui/base.py", line 865, in menu_finished
    callback()

  File "chemical_abundances.py", line 1413, in refresh_current_model
    self.measurement_view.update_row(proxy_index.row())

AttributeError: 'NoneType' object has no attribute 'row'
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/br8wb/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
This error indicates you do not have any measurements loaded in the table
(closing).
