### ISSUE TITLE
Exception raised: u'transition_hashes'

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#293]
An exception was encountered using version 4f7f523* on Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/gui/ui_mainwindow.py", line 369, in open_session
    self.session = smh.Session.load(path)

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/session.py", line 421, in load
    args = [session, state["transition_hashes"]]

KeyError: u'transition_hashes'
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/xyntI/screenshot.png)

**Additional details on how this exception occurred**:
Can't open a smh file, i might have open that in a different smh branch would that make a difference?

**Comment by alexji** [comment]
Yes it looks like this is an SMH v1 file. You can convert it to v2. Closing.
