### ISSUE TITLE
Exception raised: cannot import name wraps

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#297]
An exception was encountered using version 4f7f523 on Python 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]:

````python
Traceback (most recent call last):

  File "/Users/levkendrick/smhr/smh/gui/ui_mainwindow.py", line 369, in open_session
    self.session = smh.Session.load(path)

  File "/Users/levkendrick/smhr/smh/session.py", line 372, in load
    metadata = pickle.load(fp)

  File "/usr/local/lib/python2.7/site-packages/astropy/table/column.py", line 27, in <module>
    from ..utils.metadata import MetaData

  File "/usr/local/lib/python2.7/site-packages/astropy/utils/metadata.py", line 8, in <module>
    from ..utils import wraps

ImportError: cannot import name wraps
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/q3imS/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by maddiecain** [comment]
If it helps, this is the terminal printout when I load up SMH
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

'NoneType' object has no attribute 'metadata'
'NoneType' object has no attribute 'metadata'
'NoneType' object has no attribute 'metadata'
'NoneType' object has no attribute 'metadata'
'NoneType' object has no attribute 'metadata'
'NoneType' object has no attribute 'metadata'
'NoneType' object has no attribute 'metadata'
'NoneType' object has no attribute 'metadata'
objc[4437]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff991b5c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11e4facd8). One of the two will be used. Which one is undefined.

**Comment by alexji** [comment]
What is your version of astropy? I currently have 2.0.2.

Another thing is make sure that astropy, numpy, etc are installed with
anaconda; it looks like there may be a version mismatch.

**Comment by maddiecain** [comment]
2.0.7

**Comment by alexji** [comment]
Have not heard any more problems so closing
