### ISSUE TITLE
Exception raised: 

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#298]
An exception was encountered using version e94df1f* on Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/gui/ui_mainwindow.py", line 562, in export_spectral_model_measurements
    self.session.export_spectral_model_measurements(path)

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/session.py", line 1189, in export_spectral_model_measurements
    raise NotImplementedError

NotImplementedError
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/5Kgec/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
This feature is currently not implemented, do you need it?

**Comment by mgull19** [comment]
it worked for another star and gave me the EW which is what i need,
so i just assumed it worked, but may have done something else

**Comment by alexji** [comment]
Ah okay I got it. In v0.2, it will error if you have any synthesis models.

Two possible solutions:
(1) Switch to the dwarf-cannon branch. This is the one I'm developing on right now and I have a hack to skip over those.
(2) Make a copy of the SMH file, delete all the synthesis measurements, and then export.

Closing issue.
