### ISSUE TITLE
Master branch version bump to v0.21

### ISSUE THREAD

**Issue by alexji** [andycasey/smhr#305]
@andycasey I would like to bump the default "master" version to v0.21. This is the version that I have been working with actively, and no one is using v0.1 AFAIK.

The branch v0.1 should be retained to record that in case backwards compatability is needed.

This is motivated by the desire to make a new version 0.3, which will be a python 3 only version of the code; and port the GUI to pyqt, fixing matplotlib bugs etc. I'm planning to do this over the next few weeks.

**Comment by andycasey** [comment]
Go for it!
