### ISSUE TITLE
Request: make 'export abundance table' include the range of logeps values

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#308]
I have a script that will produce a latex'd version of the abundance table, but in order to do the small sample size errors from keeping (1962), I need it to export the range of logeps values . Is there a good way to do this?

**Comment by alexji** [comment]
Not right now and no plans to implement it; but you can export all the line measurements and find the min/max to calculate the range for this purpose.

You can look at `groupby` from `astropy.table.Table` or `DataFrame.groupby` from the `pandas` library, or you can just do boolean indexing.
