### ISSUE TITLE
"Save" not an option in menu bar

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#309]
<img width="1280" alt="screen shot 2019-01-21 at 1 18 08 am" src="https://user-images.githubusercontent.com/13720061/51456125-7e7d3200-1d1a-11e9-9a4c-230f6f2d36a7.png">

**Comment by alexji** [comment]
I've had things like this in the past where none of the menu options were activated. Usually the keyboard shortcuts work. In my experience, this has to do with opening the GUII as `ipython __main__.py` vs `python __main__.py`. I have no idea why this happens though.

If you need to save an open SMH session, find and make a copy of the temporary directory in the `~/.smh` directory.

(Closing)
