### ISSUE TITLE
Exception raised: [Errno 2] No such file or directory: u'/Users/maudegull/.smh/tmpIQDzCP/session.pkl'

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#312]
An exception was encountered using version e94df1f* on Python 2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:31:17) [GCC 4.2.1 (Apple Inc. build 5577)]:

````python
Traceback (most recent call last):

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/gui/ui_mainwindow.py", line 402, in open_session
    self.session = smh.Session.load(path)

  File "/Users/maudegull/Desktop/UROP_FREBEL/smhr/smh/session.py", line 399, in load
    with open(os.path.join(twd, "session.pkl"), "rb") as fp:

IOError: [Errno 2] No such file or directory: u'/Users/maudegull/.smh/tmpIQDzCP/session.pkl'
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/Rq4wi/screenshot.png)

**Additional details on how this exception occurred**:

Is this a "we can't find the spectra" issue?

**Comment by alexji** [comment]
No, this suggests the SMH data is not there. I suspect you are trying to
open an old SMH file.
