### ISSUE TITLE
Exception raised: No module named _multiarray_umath

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#315]
An exception was encountered using version 12eec10 on Python 2.7.15 |Anaconda, Inc.| (default, Oct 23 2018, 13:35:16) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]:

````python
Traceback (most recent call last):

  File "/Users/madelyncain/smhr-2/smhr/smh/gui/ui_mainwindow.py", line 402, in open_session
    self.session = smh.Session.load(path)

  File "/Users/madelyncain/smhr-2/smhr/smh/session.py", line 400, in load
    metadata = pickle.load(fp)

ImportError: No module named _multiarray_umath
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/xJt9g/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by maddiecain** [comment]
Happened after I downgraded bumpy

**Comment by alexji** [comment]
I suspect this is because you saved the file with a newer version of numpy
and now have an older one.

I can't think of a solution other than upgrading versions of numpy one by
one until everything works; there's got to be one in between 1.11 and what
you had before.
