### ISSUE TITLE
No module named 'PySide'

### ISSUE THREAD

**Issue by Mohammad-Mardini** [andycasey/smhr#318]
Hi,
I followed the instructions written by Alex and I think that I managed to install SMHR on my machine. However, I end with an error (please see below) once I run `ipython __main__.py`
I thought that we had installed PySide by running `conda install pyside`

I would appreciate if you can help me to go through this error.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/phd_research/smhr-master/smh/gui/__main__.py in <module>()
      8 
      9 import logging
---> 10 from PySide import QtCore, QtGui
     11 import yaml
     12 import os

ModuleNotFoundError: No module named 'PySide'

**Comment by alexji** [comment]
It seems likely that you are not using the right ipython to open SMHR.
Check “which ipython” and make sure it matches the anaconda distribution
that you used to install everything.
