### ISSUE TITLE
Can't find MOOGSILENT

### ISSUE THREAD

**Issue by Mohammad-Mardini** [andycasey/smhr#322]
Hi guys,

I'm trying to install SMHR on my fresh Mac. I followed Alex's instructions, and everything went smoothly~thanks!

However, when I try to run `ipython __main__.py` I will have the following error:

`MacBook-Pro:gui mardini$ ipython__main__.py`
`2019-07-20 15:11:53,906 [ERROR   ] Failed to find moogsilent executable
Traceback (most recent call last):`
`File "/smhr/smh/radiative_transfer/moog/utils.py", line 35, in <module> moogsilent_path`
`NameError:name 'moogsilent_path' is not defined`

Could you please help me with this issue?
Thanks in advance

**Comment by andycasey** [comment]
You have to install MOOG (well, MOOGSILENT) separately and make sure it is on your $PATH

**Comment by Mohammad-Mardini** [comment]
Thank you, it worked.
