### ISSUE TITLE
Exception raised: need more than 0 values to unpack

### ISSUE THREAD

**Issue by Mohammad-Mardini** [andycasey/smhr#328]
Hi, could you please help me with the following issue?

An exception was encountered in [this session](https://transfer.sh/6qa4w/session.smh) using version None on Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]:

````python
Traceback (most recent call last):

  File "/Users/mardini/Documents/GitHub/smhr/smh/gui/stellar_parameters.py", line 987, in solve_parameters
    self.measure_abundances()

  File "/Users/mardini/Documents/GitHub/smhr/smh/gui/stellar_parameters.py", line 696, in measure_abundances
    self.update_scatter_plots(redraw=True)

  File "/Users/mardini/Documents/GitHub/smhr/smh/gui/stellar_parameters.py", line 554, in update_scatter_plots
    _, (ex_yerr_top, ex_yerr_bot), (ybars, ) = ex_container

ValueError: need more than 0 values to unpack
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/Jy8XF/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
You might have to push measure abundances before the solve button.

If that doesn’t work, can you send the matplotib version that you are
using? Also more description about when/how this occurs.

**Comment by Mohammad-Mardini** [comment]
The matplotib version that I have is 2.0.2

After the normalization, I click the 'Normalize and stitch Orders' button, which brings up the rest of the tabs. On the Stellar parameters tab, I click the 'Measure abundances'. This tells me that there is no line list, I click 'OK' and then it brings up a prompt to ask me to load my line list (I choose to add EQW list), at this point SMHR will poop this error. I thought it is just a matter of line list issues; however, using another line list doesn't fix that.


Thank you for your time and help.

**Comment by alexji** [comment]
Can you downgrade to matplotlib v1.5.1 and see if that works?

**Comment by Mohammad-Mardini** [comment]
It is working now. I will close this issue.
Thanks
