### ISSUE TITLE
Exception raised: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by Li-Yangyang** [andycasey/smhr#330]
Hi,
I am running your test session (test_G64-12_v02.smh) with v2.0 smhr. When I get stellar parameter and press the "Measure abundance", it gave me such errors like. Do you have idea what's going on?
================Below is the error trace==================================
An exception was encountered in [this session](https://transfer.sh/VqEUp/session.smh) using version cff9479 on Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) [GCC 7.3.0]:

````python
Traceback (most recent call last):

  File "/media/yangyangli/OS/yangyangli_private/Code/NLTE/smhr/smh/gui/stellar_parameters.py", line 164, in measure_abundances
    self.parent.session.measure_abundances(spectral_models=spectral_models)

  File "/media/yangyangli/OS/yangyangli_private/Code/NLTE/smhr/smh/session.py", line 1485, in measure_abundances
    self.stellar_photosphere, transitions[finite], twd=self.twd)

  File "/media/yangyangli/OS/yangyangli_private/Code/NLTE/smhr/smh/radiative_transfer/moog/cog.py", line 98, in abundance_cog
    code, out, err = utils.moogsilent(moog_in, **kwargs)

  File "/media/yangyangli/OS/yangyangli_private/Code/NLTE/smhr/smh/radiative_transfer/moog/utils.py", line 111, in moogsilent
    stderr=subprocess.PIPE, env=env, close_fds=True)

  File "/media/yangyangli/OS/yangyangli_private/anaconda3/envs/smh/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)

  File "/media/yangyangli/OS/yangyangli_private/anaconda3/envs/smh/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

OSError: [Errno 8] Exec format error
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/OwXHd/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
What is the operating system you are running on? It seems like an issue running MOOG.

Would also help to give the output of `which MOOGSILENT`, and testing to see what happens when you just type `MOOGSILENT` into the shell.

**Comment by Li-Yangyang** [comment]
Thanks for replying!
My system is Ubuntu 18.04. And when I type MOOGSILENT, the same error pops out:
` /media/yangyangli/OS/yangyangli_private/Code/NLTE/moog17/MOOGSILENT: cannot execute binary file: Exec format error `

Yangyang

**Comment by Li-Yangyang** [comment]
Can I use MOOG not MOOGSILENT in smhr? Because when I type MOOG, MOOG work out without such issues. 

I think it is installing MOOG17scat successfully without MOOGSILENT mode. Because I met some issues about library not finding when I do with MOOGSILENT mode...

**Comment by alexji** [comment]
OK that will do it! We do need MOOGSILENT unfortunately. If you are on Ubuntu you probably will need to modify whatever Makefile you used to install.

I don't remember exactly, but you can look at Makefile.maclapsilent and duplicate the corresponding changes in whatever Makefile you decided to install.

This is a moog17scat installation issue so I am closing this issue. You can raise an issue there (https://github.com/alexji/moog17scat/issues) if you have continued difficulty.
