### ISSUE TITLE
Git Merge artifact in `linelist.py`

### ISSUE THREAD

**Issue by AYelland** [andycasey/smhr#340]
From your last Github merge, there is an artifact in the `linelist.py` file. It is on line 631-635 in the _read-moog()_ class method.

```
<<<<<<< HEAD
        dtypes = dtypes + [np.float32]
=======
        dtypes = dtypes + [float]
>>>>>>> py38-mpl313
```

Simple enough to fix, but throws an error when trying to open the gui.

**Comment by alexji** [comment]
Thanks, fixed now in master.

Worth noting that the dev branch is py38-mpl313, which ironically tends to be more stable (because I use it a lot).

**Comment by AYelland** [comment]
Good to know! Thank you :)

Alex Yelland

From: Alex Ji ***@***.***>
Reply-To: andycasey/smhr ***@***.***>
Date: Sunday, June 16, 2024 at 2:35 PM
To: andycasey/smhr ***@***.***>
Cc: AY3 ***@***.***>, Author ***@***.***>
Subject: Re: [andycasey/smhr] Git Merge artifact in `linelist.py` (Issue #340)


Thanks, fixed now in master.

Worth noting that the dev branch is py38-mpl313, which ironically tends to be more stable (because I use it a lot).
