### ISSUE TITLE
Chemical abundances tab

### ISSUE THREAD

**Issue by andycasey** [andycasey/smhr#40]
At least:
- [x] Integrate treeview
- [x] Include MPL widget for viewing spectra + masking regions, etc
- [x] Model options GUI
- [x] Be able to specify full abundance table, isotope entries and model parameters for a synthesis model
- [ ] Calculate complexity function

EDIT:
- [x] Right-click to set multiple model options
- [x] Press enter to fit 
- [ ] Press enter in synth

EDIT2:
- [ ] Sort chemical abundance table
- [ ] Hide/unhide unchecked lines
- [ ] Reintroduce splitters? (They are REALLY helpful for UI, but there is a super weird bug where they make the window slowly grow with time...has to do with the interaction of the profile option dialog with the splitter, but not sure how. Probably needs to be QtDesigner mapped.)

**Comment by alexji** [comment]
Closing, this is for the old chemical abundances tab.
