### ISSUE TITLE
Non-LTE corrections to EWs

### ISSUE THREAD

**Issue by andycasey** [andycasey/smhr#41]
Need:
- [x] Many (>10) files containing EW NLTE corrections so that interolation can be tested.
- [x] Custom class to read in a grid and interpolate corrections
- [ ] Must be specified as part of the model in `defaults.yaml`
- [ ] If used, the grid should be saved with the session

**Comment by alexji** [comment]
This now has remained unfinished for so long that I think we should just plan to not include it in the main SMH package. If it is implemented, I think it should probably be done in an external NLTE package and imported in with some interface defined by that package. An issue/PR should then be created for that purpose.

@ranaezz @andycasey do you have any objections? If so, I will close this issue.

**Comment by andycasey** [comment]
No objections — I agree with you!

**Comment by ranaezz** [comment]
Apologies for late reply. No problem @AlexJi.. As you see fit and best for SMH.
