### ISSUE TITLE
Complete review of what happens when a new session is loaded over an old session

### ISSUE THREAD

**Issue by andycasey** [andycasey/smhr#53]
Review this and create issues! Then resolve them.

At the same time, homogenise the method names between tabs for when new session is triggered.

**Comment by alexji** [comment]
In v0.2 this works pretty well except for rv and normalization tabs.

**Comment by alexji** [comment]
This is broken for the stellar parameters tab in a bad way, causing the entire thing to break. There are problems with the caching, and measuring abundances does not reset everything.

The easiest solution is to refactor to use the same table/plotting code as the chemical abundances tab, which has proper state calculations.

**Comment by alexji** [comment]
This is now fixed for the SPtab. Adding separate new issues to redo the radial velocity and normalization tabs
