### ISSUE TITLE
Export general files

### ISSUE THREAD

**Issue by andycasey** [andycasey/smhr#76]
- [x] Normalized rest-frame spectrum
- [ ] Original input spectra
- [x] Reproducible synthesis files for MOOG (e.g., line list input, model photosphere, batch par input, etc)

**Comment by alexji** [comment]
Not the original input spectra, but everything else is done.

I also have added something to export the coadded flux and continuum, which I have used for coadding spectra from multiple files (because fitting continuum here is really good).
